<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Client_model');
    } 

    /*
     * Listing of client
     */
    function index()
    {
        if (!$this->session->userdata('admin_logged'))
        {
            redirect('admin/login');
        } 

        $data['client'] = $this->Client_model->get_all_client();
        
        $data['_view'] = 'client/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new client
     */
    function add()
    {   
        if (!$this->session->userdata('admin_logged')){ redirect('admin/login');} 

        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $client_id = $this->Client_model->add_client($params);
            redirect('client/index');
        }
        else
        {            
            $data['_view'] = 'client/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a client
     */
    function edit()
    {   
        if (!$this->session->userdata('admin_logged')){ redirect('admin/login');} 
        // check if the client exists before trying to edit it
        $id = $this->input->post('edit-id');
        $data['client'] = $this->Client_model->get_client($id);
        
        if(isset($data['client']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('edit-name'),
                );

                $this->Client_model->update_client($id,$params);            
                redirect('client/index');
            }
            else
            {
                $data['_view'] = 'client/index';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The client you are trying to edit does not exist.');
    } 

    /*
     * Deleting client
     */
    function remove($id)
    {
        if (!$this->session->userdata('admin_logged')){ redirect('admin/login');} 
        $client = $this->Client_model->get_client($id);

        // check if the client exists before trying to delete it
        if(isset($client['id']))
        {
            $this->Client_model->delete_client($id);
            redirect('client/index');
        }
        else
            show_error('The client you are trying to delete does not exist.');
    }
    
}
