<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contact_page_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contact_page by 
     */
    function get_contact_page($id)
    {
        return $this->db->get_where('contact_page',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all contact_page
     */
    function get_all_contact_page()
    {
        //$this->db->order_by('', 'desc');
        return $this->db->get('contact_page')->result_array();
    }
        
    /*
     * function to add new contact_page
     */
    // function add_contact_page($params)
    // {
    //     $this->db->insert('contact_page',$params);
    //     return $this->db->insert_id();
    // }
    
    /*
     * function to update contact_page
     */
    function update_contact_page($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('contact_page',$params);
    }
    
    // /*
    //  * function to delete contact_page
    //  */
    // function delete_contact_page($)
    // {
    //     return $this->db->delete('contact_page',array(''=>$));
    // }
}
