<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Showcase_page_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get showcase_page by 
     */
    function get_showcase_page($id)
    {
        return $this->db->get_where('showcase_page',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all showcase_page
     */
    function get_all_showcase_page()
    {
        //$this->db->order_by('i', 'desc');
        return $this->db->get('showcase_page')->result_array();
    }
        
    /*
     * function to add new showcase_page
     */
    // function add_showcase_page($params)
    // {
    //     $this->db->insert('showcase_page',$params);
    //     return $this->db->insert_id();
    // }
    
    // /*
    //  * function to update showcase_page
    //  */
    function update_showcase_page($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('showcase_page',$params);
    }
    
    // /*
    //  * function to delete showcase_page
    //  */
    // function delete_showcase_page($)
    // {
    //     return $this->db->delete('showcase_page',array(''=>$));
    // }
}
