<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Showcase_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get showcase by id
     */
    function get_showcase($id)
    {
        return $this->db->get_where('showcase',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all showcase
     */
    function get_all_showcase()
    {
        $this->db->order_by('position', 'asc');
        return $this->db->get('showcase')->result_array();
    }
        
    /*
     * function to add new showcase
     */
    function add_showcase($params)
    {
        $this->db->insert('showcase',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update showcase
     */
    function update_showcase($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('showcase',$params);
    }
    
    /*
     * function to delete showcase
     */
    function delete_showcase($id)
    {
        return $this->db->delete('showcase',array('id'=>$id));
    }
}
